Repository CS2103JAN2018-F09-B4/main, pull requests merged in 2018-03, with the labels that each got.

#27 Added: User stories to developer guide
  docs/DeveloperGuide.adoc
Labels: type.story

#69 add UniqueAppointmentList class
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
Labels: type.task

#84 Add Godxin image for AboutUs.adoc
  docs/images/Godxin.jpg
Labels: ready.for.review.and.merge

#70 Add model and addressbook data for clients and vetTechnicians in AddressBook
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: ready.for.review.and.merge, type.enhancement

#103 List displays to work with commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/ui/ChangeListTabEvent.java
  src/main/java/seedu/address/commons/events/ui/ClientPanelSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/VetTechnicianPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PetListPanel.java
  src/main/java/seedu/address/ui/VetTechnicianCard.java
  src/main/java/seedu/address/ui/VetTechnicianListPanel.java
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/VetTechnicianListPanel.fxml
  src/test/java/guitests/guihandles/ClientCardHandle.java
  src/test/java/guitests/guihandles/ClientListPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: ready.for.review.and.merge, type.task

#108 Add duration to schedule an appointment
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Duration.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentCloseToNextException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentCloseToPreviousException.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/UniqueAppointmentListTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
Labels: type.enhancement, type.epic, type.task

#107 Add pet to client feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/addpettoclientSequence.png
  docs/images/addpettoclient_logic_command_class_diagram.png
  docs/images/addpettoclientmodelclassdiagram.png
  src/main/java/seedu/address/logic/commands/AddPetToClientCommand.java
  src/main/java/seedu/address/logic/parser/AddPetToClientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/association/ClientOwnPet.java
  src/main/java/seedu/address/model/association/exceptions/ClientAlreadyOwnsPetException.java
  src/main/java/seedu/address/model/association/exceptions/ClientPetAssociationNotFoundException.java
  src/main/java/seedu/address/model/association/exceptions/PetAlreadyHasOwnerException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetToClientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPetToClientCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPetToClientCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalAddressBook.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.enhancement

#111 UGDG update: describe implementation of "pet" feature as a whole
  docs/DeveloperGuide.adoc
  docs/images/pet_diagram_snippet.png
Labels: type.document

#126 UG: add duration in schedule
  docs/UserGuide.adoc
Labels: ready.for.review.and.merge, type.document

#129 Addappttopet command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentToPetCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentToPetCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/association/exceptions/PetAlreadyHasAppointmentException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
Labels: type.enhancement

#132 Auto complete enhancement
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/autocomplete/Trie.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/autocomplete/AutoCompleteTest.java
  src/test/java/seedu/address/logic/autocomplete/TrieTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: type.enhancement

#141 RemoveAppointmentFromPetCommand + Storage integration
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/commands/AddAppointmentToPetCommand.java
  src/main/java/seedu/address/logic/commands/RemoveAppointmentFromPetCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemoveAppointmentFromPetParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentHasBeenTakenException.java
  src/main/java/seedu/address/storage/XmlAdaptedAppointment.java
  src/test/java/seedu/address/logic/commands/AddAppointmentToPetCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentToPetCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: ready.for.review.and.merge, type.enhancement
