Repository CS2103JAN2018-F09-B4/main, pull requests merged in 2018-04, with the labels that each got.

#167 Deleting a client now deletes all pets and association in list
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
Labels: type.enhancement

#171 Add Reschedulecommand to edit details of an appointment
  src/main/java/seedu/address/logic/commands/RescheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RescheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddAppointmentToPetCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RescheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/RescheduleAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.enhancement, type.epic, type.task

#173 Update UserGuide with rescheduleCommand
  collated/functional/Godxin-functional.md
  collated/functional/jonathanwj-reused.md
  collated/functional/jonathanwj.md
  collated/functional/md-azsa.md
  collated/test/Godxin-test.md
  collated/test/jonathanwj-reused.md
  collated/test/jonathanwj.md
  collated/test/md-azsa-reused.md
  collated/test/md-azsa.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/model/appointment/Duration.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentCloseToNextException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentCloseToPreviousException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentHasBeenTakenException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentListIsEmptyException.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/appointment/exceptions/DuplicateAppointmentException.java
  src/test/java/seedu/address/model/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.document

#202 SortCommands: Fix comparison bug
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: ready.for.review.and.merge

#210 Ugdg update
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentAutoCompleteClassDiagram.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/LogicAutoCompleteClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: do.not.merge.yet

#229 UserGuide update
  docs/UserGuide.adoc
  docs/images/userguide_reschedule1.png
  docs/images/userguide_reschedule2.png
Labels: type.document

#233 Unschedule appointment
  docs/UserGuide.adoc
  docs/images/userguide_unscheduleCommand_image.PNG
  docs/images/userguide_unscheduleCommand_image2.PNG
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/UnscheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnscheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPetCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveAppointmentFromPetCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/UnscheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/UnscheduleCommandParserTest.java
Labels: type.enhancement

#230 Fix bugs in validating date
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
Labels: type.bug

#240 update DG
  docs/DeveloperGuide.adoc
Labels: type.document

#242 Az dg update/ppp
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: do.not.merge.yet

#252 fix clear listallpanel
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.bug

#253 Ugdg updates
  docs/UserGuide.adoc
Labels: do.not.merge.yet

#254 UGDG update: appointment related
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AppointmentClassDemo3.pptx
  docs/diagrams/ModelAppointmentClassDiagram.pptx
  docs/images/AppointmentClassDemo3.png
  docs/images/ModelAppointmentClassDiagram.png
  docs/images/userguide_reschedule1.1.png
  docs/images/userguide_reschedule1.2.png
  docs/images/userguide_reschedule1.png
  docs/images/userguide_reschedule2.1.png
  docs/images/userguide_reschedule2.2.png
  docs/images/userguide_reschedule2.png
  docs/images/userguide_schedule.png
Labels: ready.for.review.and.merge, type.document

#259 Reschedule now retain client, pet and vetTech
  src/main/java/seedu/address/logic/commands/RescheduleCommand.java
  src/main/java/seedu/address/model/appointment/Appointment.java
Labels: type.bug
